apiVersion: v1
kind: Pod
spec:
  nodeSelector:
    kubernetes.io/arch: amd64
  volumes:
  - name: docker-socket
    hostPath: 
        path: /var/run 
  containers:
  - name: docker
    image: docker:19.03.1
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 1000m
        memory: 1Gi
    readinessProbe:
      exec:
        command: [sh, -c, "ls -S /var/run/docker.sock"]
    command:
    - sleep
    args:
    - 99d
    volumeMounts:
    - name: docker-socket
      mountPath: /var/run
